steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--tag', 'gcr.io/$PROJECT_ID/infra-as-code-tools:wip', '--file', 'Dockerfile_gcloud-full' ]
images:
- 'gcr.io/$PROJECT_ID/infra-as-code-tools:wip'
