name: Docker Image CI

on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env: 
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_REPO_OWNER: ${{ github.repository_owner }}
      run: |
        echo ${GITHUB_REPO}
        echo ${GITHUB_REPO_OWNER}
        docker build . --file Dockerfile --tag toto:$(date +%s) --target tf --build-arg TERRAFORM_VERSION=0.14.8
